Feature/header component
isdi-coders-2023/Piratas-Desmembrados-202301-bcn pull request #26
Opened 2023-02-08 22:10 UTC by AnaCatanaR

2023-02-08 23:17 UTC, lfilella97 commented on src/components/Header/HeaderStyled.tsx
> +    rotate: 34deg;
wow! no coneixia aixo!

2023-02-08 23:19 UTC, lfilella97 commented on src/components/Header/Header.tsx
> +        width="48"
esta perfe pero no se si el with i el height l'haurem de passar per promp ja que haurem de pensar en afegir el media querry per fer el component responsive

2023-02-08 23:56 UTC, AnaCatanaR commented on src/components/Header/Header.tsx
> +        width="48"
Això no ho he pensat.  Demà ho podrem comentar pel mati?

2023-02-09 08:29 UTC, lfilella97 approved these changes

2023-02-09 08:37 UTC, a9nna requested changes
Try to use getByRole instead of getByAltTest

2023-02-09 08:37 UTC, a9nna commented on src/components/Header/Header.test.tsx
> +      const expectedResult = screen.getByAltText(textLogo);
Try to use getByRole instead of getByAltText

2023-02-09 08:42 UTC, a9nna approved these changes

2023-02-09 08:42 UTC, merged